### ISSUE TITLE
DBに関する例外が発生した場合

### ISSUE THREAD

**Issue by ghost** [tamoto-takuya/tamoto_takuya#11]
https://github.com/tamoto-takuya/tamoto_takuya/blob/f7a4c055b164f3f60395f0fa85d8072428e38855/src/chapter7/controller/SettingsServlet.java#L81-L83

この実装だと、DBの例外内容をコンソールに書き出してTopページへリダイレクトするという動きになります。
つまり、発生した問題については、ユーザーに通知されることなく流れてしまいます。

**Comment by tamoto-takuya** [comment]
例外が発生した際の処理を追加しました。

**Comment by ghost** [comment]
実際の対応内容と上記のコメント内容違いません？
また、NoRowsUpdatedRuntimeExceptionをキャッチした際は支店と部署役職リスト保持していないですが、大丈夫でしょうか？

**Comment by tamoto-takuya** [comment]
コメント修正しておりませんでした。
サーブレット内のDBの例外内容については、不必要の為、削除しております。
NoRowsUpdatedRuntimeExceptionをキャッチした際は支店と部署役職リスト保持については、
保持するよう変更かけております。

**Comment by ghost** [comment]
このIssueで書くべき内容か、判断困りましたが、LoginID重複時の動作って確認しましたか？
現状のコードだと、レスポンスが2重送信されると思います。確認お願いします。

**Comment by tamoto-takuya** [comment]
進捗面談時に修正しています。

**Comment by tamoto-takuya** [comment]
進捗面談時にコードの場所を変更しております。

**Comment by ghost** [comment]
SignUpServletも対応しましょう

**Comment by tamoto-takuya** [comment]
SignUpServletもレスポンス2重送信されないよう
コードを変更しております。

**Comment by ghost** [comment]
コメントに修正箇所のリンクを付けるとかしてもらってもいいですか

**Comment by tamoto-takuya** [comment]
https://github.com/tamoto-takuya/tamoto_takuya/blob/a69887285f6cbb24938a3f1678aa0459b15f0745/src/chapter7/controller/SignUpServlet.java#L52-L71
コードを引用するのに手間取りました。
遅くなり申し訳ありません！

**Comment by ghost** [comment]
OK
