### ISSUE TITLE
id?

### ISSUE THREAD

**Issue by ghost** [tamoto-takuya/tamoto_takuya#12]
https://github.com/tamoto-takuya/tamoto_takuya/blob/f7a4c055b164f3f60395f0fa85d8072428e38855/src/chapter7/controller/SignUpServlet.java#L56

変数名が「id」となってますけど、実際に入る数値はidではないかと思いますが。。。

**Comment by tamoto-takuya** [comment]
修正しています。

**Comment by ghost** [comment]
内容としては良いですが、**どこをどのように**対応したのかコメントに記載するようにしましょうね。
（ソース埋め込みがあれば尚可）
修正で行番号も変わってしまっている中から当該箇所を探し出さなければならないレビュワーの身になってください。
