### ISSUE TITLE
変数宣言

### ISSUE THREAD

**Issue by ghost** [tamoto-takuya/tamoto_takuya#13]
constって意味わかりますか？
あと、エラーがあった時ちゃんとsubmit中止されてますかね？

https://github.com/tamoto-takuya/tamoto_takuya/blob/411430ce24c5f1d201df8ccb153fb2b1c699aa19/WebContent/signup.jsp#L79

**Comment by tamoto-takuya** [comment]
https://github.com/tamoto-takuya/tamoto_takuya/blob/931f1a575adb90527c41d029896233b77139bcbd/WebContent/signup.jsp#L77-L120

constは変数宣言するためにつけていましたが、
varに変更。エラー時にfalseを代入したかった為です。
has_errorについても、isValidに変更。
有効もしくは、無効を判断する為。
submit時エラーがあれば中止、なければ登録の動作は確認できております。
確認よろしくお願いいたします。

**Comment by ghost** [comment]
const がまだ残ってますね。
ちなみにconstは定数

**Comment by tamoto-takuya** [comment]
https://github.com/tamoto-takuya/tamoto_takuya/blob/dcf4e38157a82826a998b0ea97ba74543555cba6/WebContent/signup.jsp#L77-L120

constをvarに変更しています。
