### ISSUE TITLE
戻り値の返却

### ISSUE THREAD

**Issue by ghost** [tamoto-takuya/tamoto_takuya#14]
```javascript
  return !has_error;
```
でよくないですか？

https://github.com/tamoto-takuya/tamoto_takuya/blob/411430ce24c5f1d201df8ccb153fb2b1c699aa19/WebContent/signup.jsp#L115-L119

**Comment by tamoto-takuya** [comment]
https://github.com/tamoto-takuya/tamoto_takuya/blob/931f1a575adb90527c41d029896233b77139bcbd/WebContent/signup.jsp#L119

変数名変更に伴い、修正しております。
