### ISSUE TITLE
elementの指定方法が統一されてない

### ISSUE THREAD

**Issue by ghost** [tamoto-takuya/tamoto_takuya#16]
https://github.com/tamoto-takuya/tamoto_takuya/blob/931f1a575adb90527c41d029896233b77139bcbd/WebContent/signup.jsp#L83-L84

getElementByIdを使うのか、ID名を直接指定してつかうのか？
はっきりさせましょう

**Comment by ghost** [comment]
```
nameError.style.display = "block";
```
でも良いってことでは？

**Comment by tamoto-takuya** [comment]
https://github.com/tamoto-takuya/tamoto_takuya/blob/dcf4e38157a82826a998b0ea97ba74543555cba6/WebContent/signup.jsp#L81-L88

IDを直接指定するように変更しています。

**Comment by ghost** [comment]
ざんね～ん

```
				var password = document.getElementById("password").value;
```
↑こいつは

```
				var passwordValue = password.value;
```
↑ こうできませんか？

**Comment by tamoto-takuya** [comment]
https://github.com/tamoto-takuya/tamoto_takuya/blob/404067efd68af99d0151d8ffb29943ab3959162b/WebContent/signup.jsp#L100-L117

パスワード、確認用パスワードともに修正しております。
