### ISSUE TITLE
Sessionにユーザー入れてますが。。。

### ISSUE THREAD

**Issue by ghost** [tamoto-takuya/tamoto_takuya#2]
https://github.com/tamoto-takuya/tamoto_takuya/blob/3b3b97b8653e6b06b743e54b76a546bb5f543620/src/chapter7/controller/SettingsServlet.java#L63

これ、なんのためにやっているかわかりますか？

**Comment by tamoto-takuya** [comment]
セッションスコープを使用して
user情報を保持する目的で使ってましたが必要ありませんでした。
