### ISSUE TITLE
ユーザーの状態のカラム

### ISSUE THREAD

**Issue by ghost** [tamoto-takuya/tamoto_takuya#3]
> status` varchar(10) DEFAULT NULL,

みんなユーザーのステータスに文字突っ込んでるけど、談合してるのかな？
数値かなにかに変えましょう。停止中を表現する値と活動中を表現する値を決めましょう。

これ、多言語対応しろって言われたらこのシステム作り直しだねぇ

**Comment by tamoto-takuya** [comment]
数値に変更しています！
