### ISSUE TITLE
SQLインジェクション対策

### ISSUE THREAD

**Issue by ghost** [tamoto-takuya/tamoto_takuya#6]
https://github.com/tamoto-takuya/tamoto_takuya/blob/5400636e8eb8e6fd79e2a82ec042ee05cfd080c4/src/chapter7/dao/UserDao.java#L242

悪さされないように以下復習しましょう
https://github.com/alhinc/fukuoka-training/wiki/%E7%AC%AC6%E7%AB%A0-%E3%83%87%E3%83%BC%E3%82%BF%E3%83%99%E3%83%BC%E3%82%B9%E6%93%8D%E4%BD%9C#2-sql%E3%82%A4%E3%83%B3%E3%82%B8%E3%82%A7%E3%82%AF%E3%82%B7%E3%83%A7%E3%83%B3

**Comment by tamoto-takuya** [comment]
修正しています。

**Comment by ghost** [comment]
https://github.com/tamoto-takuya/tamoto_takuya/blob/a9587c4b9e926d8609a075d93372994bb8d660ec/src/chapter7/dao/UserDao.java#L67-L74

ログインIDの重複チェックでも同じようなことやってますな。
Railsじゃないので、これはだめ。

**Comment by tamoto-takuya** [comment]
SELECT文変更しております。
